version: "3.8"

services:
  db:
    image: mongo
    restart: always
    ports:
      - "${DB_PORT}:27017"
    networks:
      - fullstack

  bus:
    image: messaging-bus
    build:
      dockerfile: ./docker/bus/Dockerfile
    ports:
      - "${BUS_PORT}:${BUS_PORT}"
    depends_on:
      - db
    environment:
      DB_PORT: ${DB_PORT}
      APP_PORT: ${BUS_PORT}
    networks:
      - fullstack

  message:
    image: messaging-message
    build:
      dockerfile: ./docker/message/Dockerfile
    ports:
      - "${MESSAGE_PORT}:${MESSAGE_PORT}"
    depends_on:
      - db
    environment:
      DB_PORT: ${DB_PORT}
      APP_PORT: ${MESSAGE_PORT}
    networks:
      - fullstack

  router:
    image: messaging-router
    build:
      dockerfile: ./docker/router/Dockerfile
    ports:
      - "${ROUTER_PORT}:${ROUTER_PORT}"
    depends_on:
      - message
      - bus
    environment:
      APP_PORT: ${ROUTER_PORT}
      MESSAGE_PORT: ${MESSAGE_PORT}
      BUS_PORT: ${BUS_PORT}
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
